---
title: 'But, how far ahead is India?'
output: 
  flexdashboard::flex_dashboard:
    theme: 
      version: 4
      bootswatch: lux
      warning: '#010101'
    orientation: rows
    source_code: https://github.com/gafnts/brics-dashboard
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
pacman::p_load(
  flexdashboard, shiny, dplyr, arrow, here, echarts4r, lubridate
)

import <- function(path) read_feather(here('data', 'clean', path))

brics <- import('brics.feather')
indicators <- import('indicators.feather')
wdi <- import('wdi.feather')
un <- import('un.feather')

countries <- brics |> filter(iso2c != 'IN') |> pull(flag_country)

econ_ind <- 
  indicators |> 
  filter(dashboard == 'Economic indicators') |> 
  slice(6, 7, 4, 5) |> 
  pull(display)
```

```{r functions}
value_caption <- function(name) {
  htmltools::HTML(
    glue::glue("<p style = 'font-size : 15.5px;'> {name} </p><br/> 
                 <p style = 'font-size : 10px;'>* 2010 - 2020 average</p>")
  )
}

ten_year_mean <- function(country, var) {
    wdi |> 
    filter(iso2c == {{country}}) |> 
    filter(year >= 2010 & year <= 2020) |> 
    summarise(mean = round(mean({{var}}), 2)) |> 
    mutate(mean = paste0(mean, '%'))
}

country_filter <- function(...) {
    input$countries |> 
    as_tibble() |> 
    left_join(brics, by = c('value' = 'flag_country')) |> 
    pull(iso2c)
}

indicator_filter <- function(input, key, yank) {
    input |> 
    as_tibble() |> 
    left_join(indicators, by = c('value' = 'display')) |> 
    pull({{yank}})
}

bar_chart <- function(data, country, indicator, color) {
    data |> 
    filter(iso2c == {{country}}) |> 
    select(year, ` ` = {{indicator}}) |> 
    mutate(year = as_date(paste(year, '01', '01', sep = '-'))) |> 
    e_charts(year) |> 
    e_bar(` `, color = color) |> 
    e_legend(FALSE) |> 
    e_tooltip(trigger = "axis") 
}
```

```{r params}
india_color <- '#4B4B4B'
country_color <- '#85D09C'
```


```{css}
h4, .h4 {
  font-size: 16.5px;
  font-weight: 600;
}

.shiny-text-output {  /* chart_title  */
  font-size: 20px;
  font-weight: bold;
}
```

Economic indicators
=======================================================================

Sidebar {.sidebar data-width=265}
-------------------------------------

#### India's prospects
<br>

```{r}
selectInput(
  inputId = 'countries',
  label = 'Compare India with:', 
  choices = countries, 
  selected = countries[1]
)

selectInput(
  inputId = 'econ_indicators',
  label = 'Select an indicator:', 
  choices = econ_ind, 
  selected = econ_ind[1]
)
```

This dashboard will let you explore how India compares to the other [BRICS](https://en.wikipedia.org/wiki/BRICS) economies as measured by key economic, social and demographic indicators in an easy-to-use interface. <br><br><br>

<font size = '1px'> Data: [World Development Indicators](https://data.worldbank.org/)
<br> Forecasts: [World Population Prospects](https://population.un.org/wpp/)
<br><br> Disclaimer: Some missing data has been imputed using KNN. </font>

Row: Title
-----------------------------------------------------------------------

### {.value-box}

```{r}
renderValueBox({
  valueBox(
    value = brics |> filter(iso2c == 'IN') |> pull(flag_country),
    icon = NULL,
    color = 'warning'
  )
})
```

### {.value-box}

```{r}
renderValueBox({
  valueBox(
    value = input$countries,
    icon = NULL,
    color = 'success'
  )
})
```

Row: Value boxes
-----------------------------------------------------------------------

### Inflation {.value-box}

```{r}
renderValueBox({
  inf <- ten_year_mean('IN', inflation)
  
  valueBox(
    value = inf,
    caption = value_caption('Inflation *'),
    icon = NULL,
    color = 'warning'
  )
})
```

### Real interest rate * {.value-box}

```{r}
renderValueBox({
  i <- ten_year_mean('IN', real_interest_rate)
  
  valueBox(
    value = i,
    icon = NULL,
    color = 'warning'
  )
})
```

### Unemployment * {.value-box}

```{r}
renderValueBox({
  unem <- ten_year_mean('IN', unemployment)
  
  valueBox(
    value = unem,
    icon = NULL,
    color = 'warning'
  )
})
```

### Inflation {.value-box}

```{r}
renderValueBox({
  country <- country_filter()
  inf <- ten_year_mean(country, inflation)
  
  valueBox(
    value = inf,
    caption = value_caption('Inflation *'),
    icon = NULL,
    color = 'success'
  )
})
```

### Real interest rate * {.value-box}

```{r}
renderValueBox({
  country <- country_filter()
  i <- ten_year_mean(country, real_interest_rate)
  
  valueBox(
    value = i,
    icon = NULL,
    color = 'success'
  )
})
```

### Unemployment * {.value-box}

```{r}
renderValueBox({
  country <- country_filter()
  unem <- ten_year_mean(country, unemployment)
  
  valueBox(
    value = unem,
    icon = NULL,
    color = 'success'
  )
})
```

Row
-----------------------------------------------------------------------

```{r}
econ_plot_title <- 
  shiny::renderText({indicator_filter(
      input = input$econ_indicators, 
      yank = original_name
      )})
```

### `r econ_plot_title`

```{r}
renderEcharts4r({
   indicator <- indicator_filter(
      input = input$econ_indicators, 
      yank = name
      )
  
    bar_chart(
      data = wdi,
      country = 'IN',
      indicator = indicator,
      color = india_color
    )
  })
```

### `r econ_plot_title` 

```{r}
renderEcharts4r({
    country <- country_filter('flag_country')
    
    indicator <- indicator_filter(
      input = input$econ_indicators, 
      yank = name
      )
    
    bar_chart(
      data = wdi,
      country = country,
      indicator = indicator,
      color = country_color
    )
  })
```

Social development
=======================================================================

sidebar_social {.sidebar data-width=265}
-------------------------------------

#### India's prospects
<br>

```{r}
selectInput(
  inputId = 'social_countries',
  label = 'Compare India with:', 
  choices = countries, 
  selected = countries[1]
)

selectInput(
  inputId = 'social_indicators',
  label = 'Select an indicator:', 
  choices = c('One', 'Two', 'Three', 'Four'), 
  selected = 'One'
)
```

This dashboard will let you explore how India compares to the other [BRICS](https://en.wikipedia.org/wiki/BRICS) economies as measured by key economic, social and demographic indicators in an easy-to-use interface. <br><br><br>

<font size = '1px'> Data: [World Development Indicators](https://data.worldbank.org/)
<br> Forecasts: [World Population Prospects](https://population.un.org/wpp/)
<br><br> Disclaimer: Some missing data has been imputed using KNN. </font>

Row: Title (Social)
-----------------------------------------------------------------------

### {.value-box}

```{r}
renderValueBox({
  valueBox(
    value = brics |> filter(iso2c == 'IN') |> pull(flag_country),
    icon = NULL,
    color = 'warning'
  )
})
```

### {.value-box}

```{r}
renderValueBox({
  valueBox(
    value = input$social_countries,
    icon = NULL,
    color = 'success'
  )
})
```

Row: Value boxes
-----------------------------------------------------------------------

Climate change
=======================================================================

Demography
=======================================================================