# Data cleaning

```{r}
pacman::p_load(tidyverse, tidymodels, here, arrow)
reticulate::use_condaenv('ml39')
```

#### Import raw datasets

```{r}
import <- function(path) read_csv(here('data', 'raw', path))

indicators_raw <- import('indicators.csv')
wdi_raw <- import('data_wdi.csv')
un_raw <- import('data_un.csv')
brics_raw <- import('brics.csv')
```

### Indicators

```{r}
remove_unwanted <- function(var) {
  str_replace(var, "\\s*\\([^\\)]+\\)", "") |> 
      str_replace("\\,.*", "") 
}

indicators <- 
  indicators_raw |> 
  rename(original_name = 'name') |> 
  mutate(
    name = remove_unwanted(original_name) |> 
      snakecase::to_any_case(),
    display = remove_unwanted(original_name)
  ) |> 
  select(name, display, indicator, dashboard, original_name) |> 
  bind_rows(
    tibble(
      name = un_raw |> select(!1:2) |> colnames(),
      display = un_raw |> 
        select(!1:2) |> 
        colnames() |> 
        str_replace('_', ' ') |> 
        str_to_title(),
      indicator = un_raw |> select(!1:2) |> colnames(),
      dashboard = rep('Demography', 4),
      original_name = un_raw |> select(!1:2) |> colnames()
    )
  )
```

```{r}
indicators |> 
  # DISPLAY
  # Social indicators
  mutate(
    display = replace(
      display,
      display == 'Poverty headcount ratio at $2.15 a day (% of population)',
      'Poverty headcount ratio'),
    display = replace(
      display,
      display == 'Government expenditure on education',
      'Education expenditure'),
    display = replace(
      display,
      display == 'Labor force participation rate',
      'Labor force participation'),
    display = replace(
      display,
      display == 'Proportion of seats held by women in national parliaments',
      'Women in national parliaments'),
    # Environmental indicators
    display = replace(
      display,
      display == 'Electric power consumption',
      'Electricity consumption'),
    display = replace(
      display,
      display == 'Renewable energy consumption',
      'Renewable energy'),
  ) |> 
  # ORIGINAL NAME
  # Social indicators
  mutate(
    original_name = replace(
      original_name,
      original_name == 'Poverty headcount ratio at $2.15 a day (2017 PPP) (% of population)',
      'Poverty headcount ratio ($2.15 a day) (% of population)'
    ),
    original_name = replace(
      original_name,
      original_name == 'Government expenditure on education, total (% of GDP)',
      'Government expenditure on education (% of GDP)'
    ),
    original_name = replace(
      original_name,
      original_name == 'Adolescent fertility rate (births per 1,000 women ages 15-19)',
      'Adolescent fertility rate (births per 1,000 women) (ages 15-19)'
    ),
    original_name = replace(
      original_name,
      original_name == 'Labor force participation rate, female (% of female population ages 15+)',
      'Labor force participation rate (% of female population)'
    ),
  # Environmental indicators
    original_name = replace(
        original_name,
        original_name == 'Renewable energy consumption (% of total final energy consumption)',
        'Renewable energy consumption (% of total consumption)'
      ),
  ) |> 
  write_feather(here('data', 'clean', 'indicators.feather'))
```

### World development indicators

```{r}
missing <- 
  function(data) {
    data |> 
    summarise(
      across(
        .cols = everything(),
        .fns = ~ sum(is.na(.))
      )
    ) |> 
    print(
      n = Inf,
      width = Inf
    )
}
```

```{r}
wdi <- 
  wdi_raw |> 
  filter(year >= 2000 & year <= 2020)

wdi |> 
  group_by(country) |> 
  missing()
```

#### Tidy impute

```{r}
rec <- 
  recipe(
    year ~ .,
    data = wdi
  ) |> 
  step_impute_knn(all_predictors(), neighbors = 3)

wdi_rec <- 
  rec |> 
  prep() |> 
  juice() |> 
  select(iso2c, country, year, everything())

wdi_rec |> group_by(country) |> missing()
```

#### Renaming variables

```{r}
new_names <- indicators |> slice(1:22) |> pull(name)

wdi <- 
  wdi_rec |> 
  select(4:25) |> 
  set_names(new_names) |> 
  bind_cols(
    wdi_rec |> select(iso2c, year)
  ) |> 
  select(iso2c, year, everything()) |> 
  write_feather(here('data', 'clean', 'wdi.feather'))
```

#### Sklearn impute

```{python}
py_wdi = r.wdi
incomplete_rows = py_wdi[py_wdi.isnull().any(axis=1)]
incomplete_rows
```

```{r}
library(reticulate)

py$incomplete_rows |> 
  as_tibble() |> 
  print(
    n = Inf,
    width = Inf
  )
```

```{python}
import pandas as pd
from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=3)
py_wdi_num = py_wdi.drop(['iso2c', 'country'], axis=1)

py_wdi_impute = pd.DataFrame(
  imputer.fit_transform(py_wdi_num), 
  columns = py_wdi_num.columns
)
  
py_wdi_impute
```

```{python}
py_wdi_impute.isna().any()
```

### UN World Population Prospects

```{r}
un_raw |> 
  write_feather(here('data', 'clean', 'un.feather'))
```

### Countries

```{r}
brics_raw |> 
  mutate(
    flag_country = paste(flag, country_name)
  ) |> 
  write_feather(here('data', 'clean', 'brics.feather'))
```
